# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  apiavocados:
    image: apiavocados
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5262:5262
