// <auto-generated />
using System;
using ApiAvocados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiAvocados.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20231014160719_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiAvocados.Models.AttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hardiness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Taste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attribute", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea5a8e7f-a7a4-48fb-9a35-0c733d66492b"),
                            Description = "A relatively new cultivar, it was, the pretty boy baby, discovered in South Africa in the early 1990s by Mr. A.G. (Dries) Joubert. Maluma Babyy. It is a chance seedling of unknown parentage",
                            Hardiness = "1 °C",
                            Shape = "Oval",
                            Taste = "Catchy, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("c646a335-4aa4-4c76-b93b-dc681aed5bd8"),
                            Description = "The Fuerte avocado is the second largest commercial variety behind Hass. It is a long time California commercial variety valued for its winter season ripening and its B-Type blossom type which most growers plant adjacent to the Hass for a more consistent production cycle. This avocado tends to produce heavily in alternate years.",
                            Hardiness = "-1 °C",
                            Shape = "Pear",
                            Taste = "Magnificent, is a strong avocado"
                        },
                        new
                        {
                            Id = new Guid("0d22fddc-da84-48d2-8df8-396879eab809"),
                            Description = "A seedling bred from 'Hass' x 'Thille' in 1982, 'Gwen' is higher yielding and more dwarfing than 'Hass' in California. The fruit has an oval shape, slightly smaller than 'Hass' (100–200 g or 3.5–7.1 oz), with a rich, nutty flavor. The skin texture is more finely pebbled than 'Hass', and is dull green when ripe. It is frost-hardy down to −1 °C (30 °F)",
                            Hardiness = "−1 °C",
                            Shape = "Plump",
                            Taste = "Superb, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("8bf12218-74ab-4d8a-b076-771e51ddf765"),
                            Description = "Developed by a farmer, James Bacon, in 1954, Bacon has medium-sized fruit with smooth, green skin with yellow-green, light-tasting flesh. When ripe, the skin remains green, but darkens slightly, and fruit yields to gentle pressure. It is cold-hardy down to −5 °C (23 °F)",
                            Hardiness = "−5 °C",
                            Shape = "Oval",
                            Taste = "Creamy, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("a61ad1c0-6537-40e8-a56a-67874c251589"),
                            Description = "The 'Hass' is the most common cultivar of avocado. It produces fruit year-round and accounts for 80% of cultivated avocados in the world.[21][55] All 'Hass' trees are descended from a single 'mother tree' raised by a mail carrier named Rudolph Hass, of La Habra Heights, California.[20][55] Hass patented the productive tree in 1935. The 'mother tree', of uncertain subspecies, died of root rot and was cut down in September 2002.[21][55][56] 'Hass' trees have medium-sized (150–250 g or 5.3–8.8 oz), ovate fruit with a black, pebbled skin. The flesh has a nutty, rich flavor with 19% oil. A hybrid Guatemalan type can withstand temperatures to −1 °C (30 °F)",
                            Hardiness = "−1 °C",
                            Shape = "Oval",
                            Taste = "Gorgeous, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("b0ef7a5d-1a30-4f5f-b442-bbc058687832"),
                            Description = "The Lamb Hass avocado is a cross between a Hass and Gwen avocado. The fruits are larger in size and later maturing than Hass. It is gaining in popularity as a commercial and backyard variety due to its exceptional flavor and easy peeling qualities. The tree has an upright, compact habit.",
                            Hardiness = "-2 °C",
                            Shape = "Obovate",
                            Taste = "Great, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("d5712419-9ff3-4147-b470-7a95c8cc1c7d"),
                            Description = "First grown on the Pinkerton Ranch in Saticoy, California, in the early 1970s, 'Pinkerton' is a seedling of 'Hass' x 'Rincon'. The large fruit has a small seed, and its green skin deepens in color as it ripens. The thick flesh has a smooth, creamy texture, pale green color, good flavor, and high oil content. It shows some cold tolerance, to −1 °C (30 °F) and bears consistently heavy crops. A hybrid Guatemalan type, it has excellent peeling characteristics",
                            Hardiness = "−1 °C",
                            Shape = "Long pear",
                            Taste = "Marvelous, is an avocado"
                        },
                        new
                        {
                            Id = new Guid("4e05fe82-69d5-44ef-b1d0-b853ced86aa3"),
                            Description = "Developed from a chance seedling found in 1948 by James S. Reed in California, this cultivar has large, round, green fruit with a smooth texture and dark, thick, glossy skin. Smooth and delicate, the flesh has a slightly nutty flavor. The skin ripens green. A Guatemalan type, it is hardy to −1 °C (30 °F). Tree size is about 5 by 4",
                            Hardiness = "-5 °C",
                            Shape = "Pear",
                            Taste = "Catchy, is an avocado"
                        });
                });

            modelBuilder.Entity("ApiAvocados.Models.AvocadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId")
                        .IsUnique();

                    b.ToTable("Avocado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fad5ce3a-ea53-446a-a57b-3641fd794f60"),
                            AttributeId = new Guid("ea5a8e7f-a7a4-48fb-9a35-0c733d66492b"),
                            Image = "http://localhost:5262/upload-image/images/maluma.jpg",
                            Name = "Maluma Hass Avocado",
                            Price = 1.15m,
                            Sku = "NUR72KCM",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("299c15bd-9d1f-40d9-a51f-2d5e38c09c0c"),
                            AttributeId = new Guid("c646a335-4aa4-4c76-b93b-dc681aed5bd8"),
                            Image = "http://localhost:5262/upload-image/images/fuerte.jpg",
                            Name = "Fuerte Avocado",
                            Price = 1.21m,
                            Sku = "AX4M8SJV",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("d47ccd86-4e27-4323-a7ea-33f410100375"),
                            AttributeId = new Guid("0d22fddc-da84-48d2-8df8-396879eab809"),
                            Image = "http://localhost:5262/upload-image/images/gwen.jpg",
                            Name = "Gwen Hass Avocado",
                            Price = 1.25m,
                            Sku = "HYA78F6J",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("f173a2f0-3a1c-4e11-844c-d0e6ca3e66a7"),
                            AttributeId = new Guid("8bf12218-74ab-4d8a-b076-771e51ddf765"),
                            Image = "http://localhost:5262/upload-image/images/bacon.jpg",
                            Name = "Bacon Avocado",
                            Price = 1.51m,
                            Sku = "BXD100BLK",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("e006beb0-c134-4dc4-86f0-f3dbd07254de"),
                            AttributeId = new Guid("a61ad1c0-6537-40e8-a56a-67874c251589"),
                            Image = "http://localhost:5262/upload-image/images/hass.jpg",
                            Name = "Hass Avocado",
                            Price = 1.39m,
                            Sku = "RMRCZN7E",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("51913335-d729-4686-9d49-2a4e2e8fb49a"),
                            AttributeId = new Guid("b0ef7a5d-1a30-4f5f-b442-bbc058687832"),
                            Image = "http://localhost:5262/upload-image/images/lamb.jpg",
                            Name = "Lamb Hass Avocado",
                            Price = 1.34m,
                            Sku = "N55229ZA",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("29176409-c767-4a18-95d9-b067516cd4de"),
                            AttributeId = new Guid("d5712419-9ff3-4147-b470-7a95c8cc1c7d"),
                            Image = "http://localhost:5262/upload-image/images/pinkerton.jpg",
                            Name = "Pinkerton Avocado",
                            Price = 1.27m,
                            Sku = "B4HZ42TM",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("ad57954f-88eb-4059-827c-fd7f9c31075b"),
                            AttributeId = new Guid("4e05fe82-69d5-44ef-b1d0-b853ced86aa3"),
                            Image = "http://localhost:5262/upload-image/images/reed.jpg",
                            Name = "Reed Avocado",
                            Price = 1.18m,
                            Sku = "ZY3T9XXC",
                            Stock = 20
                        });
                });

            modelBuilder.Entity("ApiAvocados.Models.OrdenItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvocadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvocadoId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrdenItem", (string)null);
                });

            modelBuilder.Entity("ApiAvocados.Models.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ApiAvocados.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int[]>("Roles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValue(new[] { 1 });

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ApiAvocados.Models.AvocadoEntity", b =>
                {
                    b.HasOne("ApiAvocados.Models.AttributeEntity", "Attributes")
                        .WithOne("Avocado")
                        .HasForeignKey("ApiAvocados.Models.AvocadoEntity", "AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("ApiAvocados.Models.OrdenItemEntity", b =>
                {
                    b.HasOne("ApiAvocados.Models.AvocadoEntity", "Avocado")
                        .WithMany("OrdenItems")
                        .HasForeignKey("AvocadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiAvocados.Models.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avocado");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApiAvocados.Models.OrderEntity", b =>
                {
                    b.HasOne("ApiAvocados.Models.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiAvocados.Models.AttributeEntity", b =>
                {
                    b.Navigation("Avocado");
                });

            modelBuilder.Entity("ApiAvocados.Models.AvocadoEntity", b =>
                {
                    b.Navigation("OrdenItems");
                });

            modelBuilder.Entity("ApiAvocados.Models.OrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ApiAvocados.Models.UserEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
